config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'
  get 'profiles/edit'
  get 'profiles/update'
  get 'offer_lists/index'
  resources :favourites, only: [:create, :destroy]
  resources :favourite_lists, only: [:index]
  resources :appliances do
    resources :reviews
  end
  resources :reviews, only: [ :destroy, :index ]
  resources :offers, only: [ :index, :show, :destroy ]
  resources :reviews, only: [:destroy]
  resources :offers, only: [:create, :destroy]
  resources :offer_lists, only: [:index]
  resources :bookings, only: [:create, :destroy]
  resources :booking_lists, only: [:index]

  devise_for :users
  resource :profile, only: [:show, :edit, :update]  # Singular resource for user's own profile

  root to: "appliances#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :favourite_list
  belongs_to :appliance

  validates :appliance_id, uniqueness: { scope: :favourite_list_id }
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_action :set_favourite, only: %i[ destroy ]

  # POST /favourites or /favourites.json
  def create
    @favourite = Favourite.new(favourite_params)
    @favourite.favourite_list = current_user.favourite_list
    if @favourite.save
      flash[:notice] = 'Item was successfully added!'
      render json: { message: flash[:notice] }, status: :created
    else
      flash[:alert] = 'There was an issue with creating your model.'
      render json: { message: flash[:alert], errors: @favourite.errors.full_messages }, status: 500
    end
  end

  # DELETE /favourites/1 or /favourites/1.json
  def destroy
    if @favourite.destroy!
      flash[:notice] = 'Item was successfully removed!'
      render json: { message: flash[:notice] }, status: :ok
    else
      flash[:alert] = "There was an issue with creating your model."
      render json: { message: flash[:alert], errors: @favourite.errors.full_messages }, status: 500
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favourite
      # @favourite = Favourite.find(params[:id])
      @favourite = Favourite.where(appliance_id: params[:id], favourite_list: current_user.favourite_list).first
    end

    # Only allow a list of trusted parameters through.
    def favourite_params
      params.require(:favourite).permit(:appliance_id)
    end
end

app/views/favourites/_favourite.html.erb
<div id="<%= dom_id favourite %>">
  <p>
    <strong>Name:</strong>
    <%= favourite.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= favourite.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= favourite.user_id %>
  </p>

  <p>
    <strong>Appliance:</strong>
    <%= favourite.appliance_id %>
  </p>

</div>

app/views/favourites/_form.html.erb
<%= simple_form_for(@favourite) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.association :user %>
    <%= f.association :appliance %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/favourites/edit.html.erb
<h1>Editing favourite</h1>

<%= render "form", favourite: @favourite %>

<br>

<div>
  <%= link_to "Show this favourite", @favourite %> |
  <%= link_to "Back to favourites", favourites_path %>
</div>

app/views/favourites/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Favourites</h1>

<div id="favourites">
  <% @favourites.each do |favourite| %>
    <%= render favourite %>
    <p>
      <%= link_to "Show this favourite", favourite %>
    </p>
  <% end %>
</div>

<%= link_to "New favourite", new_favourite_path %>

app/views/favourites/new.html.erb
<h1>New favourite</h1>

<%= render "form", favourite: @favourite %>

<br>

<div>
  <%= link_to "Back to favourites", favourites_path %>
</div>

app/views/favourites/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @favourite %>

<div>
  <%= link_to "Edit this favourite", edit_favourite_path(@favourite) %> |
  <%= link_to "Back to favourites", favourites_path %>

  <%= button_to "Destroy this favourite", @favourite, method: :delete %>
</div>