config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'
  get 'profiles/edit'
  get 'profiles/update'
  get 'offer_lists/index'
  resources :favourites, only: [:create, :destroy]
  resources :favourite_lists, only: [:index]
  resources :appliances do
    resources :reviews
  end
  resources :reviews, only: [ :destroy, :index ]
  resources :offers, only: [ :index, :show, :destroy ]
  resources :reviews, only: [:destroy]
  resources :offers, only: [:create, :destroy]
  resources :offer_lists, only: [:index]
  resources :bookings, only: [:create, :destroy]
  resources :booking_lists, only: [:index]

  devise_for :users
  resource :profile, only: [:show, :edit, :update]  # Singular resource for user's own profile

  root to: "appliances#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :offer_list
  belongs_to :appliance

  validates :appliance_id, uniqueness: { scope: :offer_list_id }
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: %i[ destroy ]

  # POST /offers or /offers.json
  def create
    @offer = Offer.new(offer_params)
    @offer.offer_list = current_user.offer_list

    if @offer.save
      flash[:notice] = 'Offer was successfully added!'
      render json: { message: flash[:notice] }, status: :created
    else
      flash[:alert] = 'There was an issue with the creation.'
      render json: { message: flash[:alert], errors: @favourite.errors.full_messages }, status: 500
    end
    # respond_to do |format|
    #   if @offer.save
    #     format.html { redirect_to @offer, notice: "Offer was successfully created." }
    #     format.json { render :show, status: :created, location: @offer }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @offer.errors, status: :unprocessable_entity }
    #   end
  end

  # DELETE /offers/1 or /offers/1.json
  def destroy
    @offer.destroy!

    if @offer.destroy!
      flash[:notice] = 'Offer was successfully removed!'
      render json: { message: flash[:notice] }, status: :ok
    else
      flash[:alert] = "There was an issue with the deletion."
      render json: { message: flash[:alert], errors: @favourite.errors.full_messages }, status: 500
    end
    # respond_to do |format|
    #   format.html { redirect_to offers_path, status: :see_other, notice: "Offer was successfully destroyed." }
    #   format.json { head :no_content }
    # end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_offer
    @offer = Offer.where(appliance_id: params[:id], offer_list: current_user.offer_list)
  end
  # Only allow a list of trusted parameters through.

  def offer_params
    params.require(:offer).permit(:appliance_id)
  end

  # GET /offers or /offers.json
  # def index
  #   @offers = Offer.all
  #   @appliances = Appliance.all
  # end

  # GET /offers/1 or /offers/1.json
  # def show
  # end

  # GET /offers/new
  # def new
  #   @offer = Offer.new
  # end

  # GET /offers/1/edit
  # def edit
  # end

  # # PATCH/PUT /offers/1 or /offers/1.json
  # def update
  #   respond_to do |format|
  #     if @offer.update(offer_params)
  #       format.html { redirect_to @offer, notice: "Offer was successfully updated." }
  #       format.json { render :show, status: :ok, location: @offer }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @offer.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
end

app/views/offers/_form.html.erb
<div data-controller="total-price">
  <%= simple_form_for offer, url: offers_path, method: :post do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <h4 data-total-price-target="pricePerNight" data-price="<%= appliance.price %>">
      <strong>$<%= appliance.price %></strong>
         - per day
    </h4>
    <hr>

    <div class="form-inputs">
      <%= f.hidden_field :appliance_id, value: appliance.id %>
      <div class="mt-4">
        <%= f.input :check_in_date, as: :date, input_html: {
          data: {
            total_price_target: "checkIn",
            action: "change->total-price#calculate input->total-price#calculate"
          }
        }
      %>
      </div>
      <div class="mt-4">
        <%= f.input :check_out_date, as: :date, input_html: {
          data: {
            total_price_target: "checkOut",
            action: "change->total-price#calculate input->total-price#calculate"
          }
        }
      %>
      </div>
    </div>

    <hr>
    <div class="mt-5">
      <strong>Total Price: </strong> $<span data-total-price-target="totalPrice">0</span>
    </div>
    <div class="mt-5">
      <div class="form-actions btn btn-primary", id="btn-white">
      <%= f.button :submit %>
    </div>
    </div>
  <% end %>
</div>

app/views/offers/_offer.html.erb
<div id="<%= dom_id offer %>">
  <p>
    <strong>Check in date:</strong>
    <%= offer.check_in_date %>
  </p>

  <p>
    <strong>Check out date:</strong>
    <%= offer.check_out_date %>
  </p>

  <p>
    <strong>User:</strong>
    <%= offer.user_id %>
  </p>

  <p>
    <strong>Appliance:</strong>
    <%= offer.appliance_id %>
  </p>

</div>

app/views/offers/edit.html.erb
<h1>Editing offer</h1>

<%= render "form", offer: @offer %>

<br>

<div>
  <%= link_to "Show this offer", @offer %> |
  <%= link_to "Back to offers", offers_path %>
</div>

app/views/offers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>My Offers</h1>

<% @offers.each do |offer| %>
  <div>
    <h2><%= link_to offer.appliance.name, offer_path(offer) %></h2>
    <p>Check-in: <%= offer.check_in_date %></p>
    <p>Check-out: <%= offer.check_out_date %></p>

    <% if offer.user_id.nil? %>
      <%= link_to "Book Now", book_offer_path(offer), method: :patch, class: "btn btn-primary" %>
    <% else %>
      <p><strong>Booked by:</strong> <%= offer.user.email %></p>
    <% end %>
  </div>
<% end %>

app/views/offers/new.html.erb
<h1>New offer</h1>

<%= render "form", offer: @offer %>

<br>

<div>
  <%= link_to "Back to offers", appliances_path %>
</div>

app/views/offers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @offer %>

<div>
  <%= link_to "Edit this offer", edit_offer_path(@offer) %> |
  <%= link_to "Back to offers", offers_path %>

  <%= button_to "Destroy this offer", @offer, method: :delete %>
</div>